spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins:
              - "http://localhost:8080"
            allowed-headers: "*"
            allowed-methods: "*"
            max-age: 3600
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务来路由
      routes:
        - id: jpegoptim-processing-desk #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://jpegoptim-processing-desk
          predicates:
            - Path=/jpegoptim/**   #断言,路径相匹配的进行路由

        - id: user-center
          uri: lb://user-center
          predicates:
            - Path=/user/**   #断言,路径相匹配的进行路由

server:
  port: 12001


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka11001.com:11001/eureka/,http://eureka11002.com:11002/eureka/    #设置与eureka server交互的地址，查询服务和注册服务都需要依赖这个地址
