server:
  port: 10001



spring:
  application:
    name: user-center

  redis:
    password: 123456
    port: 6379
    host: 127.0.0.1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.58.103:3306/user_center?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name: session_name
        principal-cookie-name: cookie_name
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123456
      aop-patterns: com.lizhuopeng

  servlet:
    multipart:
      max-file-size: 10MB #设置限制上传文件的大小
      max-request-size: 100MB


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.lizhuopeng.model
  config-location: classpath:Mybatis-conf.xml


eureka:
  client:
    register-with-eureka: true #是否将自己注册进Eureka
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka11001.com:11001/eureka,http://eureka11002.com:11002/eureka,http://eureka11003.com:11003/eureka/ #将自己注册到哪，注册中心Eureka的地址


ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000

logging:
  level:
    com.lizhuopeng.feign.JpegoptimProcessingDeskFeign: debug #指定具体接口在哪个环境下打印日志